name: Master Build

on:
  push:
    branches: [ "master" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run unit tests
        run: ./gradlew test

  build-local:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create local.properties
        run: echo "api_key=${{ secrets.RAWG_API_KEY }}" > local.properties
      - name: Build Local Debug APK
        run: ./gradlew assembleLocalDebug
      - name: Upload Local Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-local-debug
          path: app/build/outputs/apk/local/debug/app-local-debug.apk

  build-prod:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create local.properties
        run: echo "api_key=${{ secrets.RAWG_API_KEY }}" > local.properties
      - name: Build Prod Debug APK
        run: ./gradlew assembleProdDebug
      - name: Upload Prod Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-prod-debug
          path: app/build/outputs/apk/prod/debug/app-prod-debug.apk
