name: Master Build

on:
  push:
    branches: [ "master" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run unit tests
        run: ./gradlew testLocalDebugUnitTest

  build-local:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create local.properties
        run: echo "api_key=dummy_key_for_mock_build" > local.properties
      - name: Build Local Debug APK
        run: ./gradlew assembleLocalDebug
      - name: Upload Local Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-local-debug
          path: app/build/outputs/apk/local/debug/app-local-debug.apk

  build-mock:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create local.properties
        run: |
          echo "api_key=dummy_key_for_mock_build" > local.properties
          echo "rawg_mock_server=${{ secrets.RAWG_MOCK_SERVER }}" >> local.properties
      - name: Build Mock Debug APK
        run: ./gradlew assembleMockDebug
      - name: Upload Mock Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-mock-debug
          path: app/build/outputs/apk/mock/debug/app-mock-debug.apk

  build-prod:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > app/upload.keystore
      - name: Create local.properties
        run: |
          echo "api_key=${{ secrets.RAWG_API_KEY }}" > local.properties
          echo "KEY_PATH=upload.keystore" >> local.properties
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> local.properties
          echo "ALIAS=${{ secrets.ALIAS }}" >> local.properties
          echo "ALIAS_PASSWORD=${{ secrets.ALIAS_PASSWORD }}" >> local.properties
      - name: Build Prod Release APK
        run: ./gradlew assembleProdRelease
      - name: Upload Prod Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-prod-release
          path: app/build/outputs/apk/prod/release/app-prod-release.apk
